pipeline:
  name: test-pipeline-001
  identifier: testpipeline001
  projectIdentifier: DemoProject002
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Stage001
        identifier: Stage001
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo hello world
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
